export const REMOTION_RENDER_SERVER_PORT = 5050;
export const REMOTION_RENDER_SERVER_ORIGIN = `http://127.0.0.1:${REMOTION_RENDER_SERVER_PORT}`;
export const REMOTION_RENDER_WIDTH = 720;
export const REMOTION_RENDER_HEIGHT = 1280;
export const REMOTION_RENDER_FPS = 24;
export const REMOTION_RENDER_MAX_DURATION = 6;
export const REMOTION_RENDER_DURATION_IN_FRAMES = REMOTION_RENDER_FPS * REMOTION_RENDER_MAX_DURATION;
